name: "Delete batch GHCR versions"

description: This action can delete batch of ghcr package versions

branding:
  icon: "trash-2"
  color: "purple"

inputs:
  selector:
    description: "Selector for batch delete action"
    required: true

  excluder:
    description: "Excluder for batch delete action"
    required: false

  org:
    description: "Organization who owns the packages"
    required: true
    default: ${{ github.repository_owner }}

  package_name:
    description: "Name of the package"
    required: true
    default: ${{ github.repository }}

  package_type:
    description: "Type of the package"
    required: true
    default: "container"

  github-access-token:
    description: "Github access token"
    required: true
    default: ${{ github.token }}

  dry-run:
    description: "1 to disable delete action"
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
    - name: Clean GHCR images
      uses: actions/github-script@v5
      env:
        ORG: "${{ inputs.org }}"
        DRY_RUN: "${{ inputs.dry-run }}"
        SELECTOR: "${{ inputs.selector }}"
        EXCLUDER: "${{ inputs.excluder }}"
        PACKAGE_NAME: "${{ inputs.package_name }}"
        PACKAGE_TYPE: "${{ inputs.package_type }}"
      with:
        github-token: "${{ inputs.github-access-token }}"
        script: |
          const script = require('${{ github.action_path }}/src/entrypoints/action')
          await script({github, context, core})
